[project]
name = "guntamatic-exporter"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
    "influxdb-client>=1.26.0",
    "python-slugify==8.0.4",
    "requests>=2.28,<2.33",
    "six>=1.17.0",
    "urllib3>2",
]
